name: Build, Push, and Deploy to Server

on:
  push:
    branches: ["main"]

jobs:
  # JOB PERTAMA: MEMBANGUN IMAGE
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-project:latest

  # JOB KEDUA: DEPLOY KE SERVER (BERJALAN SETELAH BUILD SELESAI)
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # INI BAGIAN YANG ANDA CARI
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }} # Hapus baris ini jika key Anda tidak pakai passphrase
          script: |
            # Pindah ke direktori proyek (buat jika belum ada)
            mkdir -p ~/app && cd ~/app
            # Buat file docker-compose.yml terbaru dari secret
            echo '${{ secrets.DOCKER_COMPOSE }}' > docker-compose.yml
            # Tarik versi image terbaru dari Docker Hub
            docker-compose pull
            # Jalankan aplikasi (akan membuat ulang container yang berubah)
            docker-compose up -d
